class CBT {
  late String headline;
  late String imageUrl;
  late String description;

  CBT(this.headline, this.imageUrl, this.description);
}

List cbtSteps = [
  CBT("Make A List", "", "Get a sheet of paper and put a line down the middle from top to bottom. The left-hand column you’re going to title “Old Thoughts” or “Unproductive Thoughts” and the right-hand column will be “Replacement Thoughts.”"),
  CBT("Record Unproductive Thoughts", "", "In the left-hand column, start writing out unproductive thoughts that you find yourself thinking on a regular basis. These could be anxious or worried thoughts, highly negative or self-critical thoughts, thoughts that display a lack of self-confidence or are self-depreciating, or any other thoughts that hold you back or make you unhappy.  Write out these thoughts in the first person – the way they sound when you speak them to yourself."),
  CBT("Create Replacement Thoughts", "", "Now, in the right-hand column, you’re going to create a replacement thought for each unproductive thought you wrote down. When crafting your replacement thoughts there’s a few different ways to approach the process. First, you can try just writing the opposite of your negative thought – though this alone is almost always too simplistic. Another way to approach it is to ask yourself, “If my unproductive thought is a lie or is untrue in some way, then what is the truth?” Or, in less dichotomous language, if my unproductive thought is only partly true or incomplete, then what could I tell myself that would be more accurate or convey a more complete and realistic picture of my situation. The replacement thought should be more productive, constructive, and self-affirming than the original thought. Be sure that your replacement thoughts don’t consist of you lying to yourself and telling yourself that everything will be okay if that’s not necessarily true. This isn’t about self-deception. This is about coaching yourself through a difficult situation or emotional reaction in a way that focuses on the positive and affirms your ability to affect change within yourself and in the world around you."),
  CBT("Read Your List Often", "", "Start reading through your list of replacement thoughts at least twice a day. I usually recommend that clients read their lists first thing in the morning upon getting out of bed and last thing at night before jumping into bed. Over time, you will start memorizing the wording and content of your replacement thoughts, so that you can use them throughout each day."),
  CBT("Notice And Replace", "", "As you go through your day, notice when you think one of your unproductive thoughts and stop yourself.  Take a moment to reject that old way of thinking – you might envision yourself throwing that thought away in the trash. Then, speak the corresponding replacement thought to yourself and let it sink in. Don’t worry if thinking that new thought didn’t change how you feel; that will come with time. The trick to cognitive restructuring is consistency and perseverance. In the beginning, you may have to reject and replace thoughts many, many times a day. But, at some point, instead of thinking the old thoughts you will find yourself automatically thinking the replacement thoughts – and this is when you’ll know your hard work is paying off!"),
];