class Doctor {
  late String imagePath;
  late String name;
  late String hospital;
  late String yearsOfExp;
  late String specialisation; // 404
  late String education;
  late String about;
  late String phone;
  late String email; // 404
  late String website;
  late double x_cor;
  late double y_cor;
  late String address;

  Doctor(this.imagePath, this.name, this.yearsOfExp, this.specialisation,
      this.education, this.about, this.phone, this.email, this.website, this.x_cor, this.y_cor, this.address);
}

List doctors = [
  Doctor("assets/images/doctors/doc1.png", "Ms. Shrishti Dhupar", "1 Year", "Therapist", "MA - Clinical Psychology",
      "Mr Shrishti Dhupar A Mental Health Professional and has experience of working in varied clinical settings. She has equipped herself with the practical tools and techniques used in therapy. Shrishti has an immense passion in working with women facing emotional distress and abuse. Her expertise in Child and Human Development also qualifies her as a specialist among Teens and Young Adults.",
      "011 4116 8518",
      "epione2022@gmail.com",
      "https://www.practo.com/delhi/therapist/9811882090-psychologist?practice_id=1295235&specialization=Psychologist&referrer=doctor_listing&utm_source=google",
      28.566137, 77.273090, "Happitude Studio"),
  Doctor("assets/images/doctors/doc2.jpg", "Dr. Owais Akram Farooqui", "15 Years", "Therapist", "PhD - Psychology", "Dr. Owais Akram Farooqui did M.A, PGDCP, MPhil Institute of Human Behaviour and Allied Sciences (IHBAS) and Ph.D. in Clinical Neuro Psychology Jamia Millia Islamia Central University (JMI) Delhi. Presently he is working in Metro Groups of Hospitals & Dharamshila Cancer Hospital & Research Centre as a Consultant Clinical Psychologist (since 2013). He had worked in IHBAS as a Clinical Psychologist for two+ years (2002-2004). April 2007, He joined Shanti Mukund Hospital (Shanti Home advanced de addiction and Mental Health Clinic) as a Consultant Clinical Psychologist. He was the Chief Centre Coordinator and Consultant Clinical Psychologist. He had worked in Shanti Home for 6 years. Simultaneously working as a guest faculty in dept. of psychology (JMI) last from seven years. Also guest faculty In Ali Yavar Jung National Institute of Hearing Handicapped (NIHH). Several students from Different universities doing their master level project thesis under my supervision. Also Super visioning (Graduates, PG, PGDCP & MPhil,) during their internship from different Universities like: Delhi University, JMI, Amity, and GBU last from 7years. Invited to deliver lectures on Psychological problems in Govt. & Private sectors on stress/ anger / Adjustment Management etc.(Delhi Police, Schools, MTNL, BSNL, Corporate etc.). Regular appearance on T.V shows for awareness & solutions regarding psychological problems & difficulties (Sahara tv, pragya tv, P7news, 4real news, focus tv, Hamare tv etc. writing articles giving comments for print media. He has more than fourteen years experience of (Clinical, Research & Teaching).", "011 4084 9589", "epione2022@gmail.com", "https://www.practo.com/delhi/doctor/dr-owais-akram-farooqui-1?specialization=Clinical%20Psychologist&practice_id=1312534&sem=true", 28.567488, 77.268820, "Psynergy"),
  Doctor("assets/images/doctors/doc3.jpg", "Ms. Ashita Mahendru", "10 Years", "Therapist", "M.Phil - Clinical Psychology", "Dr. Ashita Mahendru is a psychologist with an M.Phil in Clinical Psychology, Member of American Psychological Association(APA) and licenses in Clinical as well as Rehabilitation Psychology, she's fit for the job profile of a clinical psychologist especially with children adolescents and young adults. she has over 5 years of experience in dealing with clients with academic difficulty and stress, adjustment issues, career and goal confusion, time management, learning Problem, Anxiety & Depression, obsessive-compulsive disorder,Friendship Issues, relationship issues, Social Pressure,Suicide, Psychosis, Self-harm, substance/drugs misuse and eating disorders,Diversity and equality issues, Child and adolescent and family psycho-social development, Bullying/Cyberbullying, Promoting protective factors and good parenting, Panic attacks, Traumatic events, Aggressive behaviors.", "011 4116 8571", "epione2022@gmail.com", "https://www.practo.com/delhi/therapist/ashita-mahendru-psychologist?practice_id=1169862&specialization=Psychologist&referrer=doctor_listing&utm_source=google", 28.836855, 77.168210, "Mind Healing Clinic"),
  Doctor("assets/images/doctors/doc4.jpg", "Dr. Ashima Srivastava", "23 Years", "Therapist", "PhD - Clinical Psychology", "Dr Ashima is RCI Registered Child and Adult Psychologist with years of experience in dealing with numerous child hood and adult-related psychological conditions. She is actively involved in imparting Counselling, Psychotherapy and is an expert in Psychological Assessments and Diagnostic Assessment. Dr.Ashima is an eminent Clinical Psychologist and an intellectually stimulating, thought-provoking professional who works in a congenial professional environment conducive for her patients. She holds an experience of 18 years in the field of Clinical Psychology. She provides Family and Relationship counselling, Behavioural Therapy, Cognitive Behaviour Therapy (CBT), Personality Assessment, Assessment of IQ and Learning disorders, and various other types of therapies and assessment services. She has also been Certified and trained from USA in 2013 in diagnosing and treating Neuro-developmental disorders like ADHD, Autism etc.", "080 4947 5024", "epione2022@gmail.com", "https://www.practo.com/delhi/therapist/ashima-shrivastava-psychologist?practice_id=723180&specialization=Psychologist&referrer=doctor_listing&utm_source=google", 28.633170, 77.309930, "Max Super Speciality Hospital"),
  Doctor("assets/images/doctors/doc5.jpg", "Ms. Rashi Ahuja", "8 Years", "Therapist", "MSc - Counselling Psychology", "A Counselor, a Practitioner & Trainer of Clinical Hypnotherapy and Neuro Linguistic Programming (NLP). She is an alumnus of Delhi University, Christ University and California Hypnosis Institute. Rashi has worked with several leading Schools, Colleges, Multi-National Companies, Hospitals and other Healthcare Organisations across the country. Having worked tirelessly for over a decade in this space, she started Happitude Studio with an aim to empower people, help them find their inner happiness and lead a life with a “Happy Attitude”.", "11411 68518", "epione2022@gmail.com", "https://www.practo.com/delhi/doctor/rashi-ahuja-psychologist?specialization=Counselling%20Psychologist&practice_id=1295235&sem=true", 28.566137, 77.273090, "Happitude Studio"),
  Doctor("assets/images/doctors/doc6.png", "Ms. Neha Gupta", "13 Years", "Therapist", "MA - Clinical Psychology", "Ms. Neha Gupta is a Hypnotherapist,Psychologist and Counselling Psychologist in Vijaynagar, Delhi and has an experience of 13 years in these fields. Ms. Neha Gupta practices at AntarMan Healthy mind in Vijaynagar, Delhi. She completed MA - Clinical Psychology from Amity University Campus, Noida in 2009,BA - Psychology from University of Delhi in 2007 and Certificate Course in Integrated Hypnotic Modalities for Behavioral Resolutions from California Institute of Integral Studies in 2007. Some of the services provided by the doctor are: Personality Assessment,Psychotherapy for Couples and Psychotherapy Adult etc.", "011 4221 3880", "epione2022@gmail.com", "https://www.practo.com/delhi/doctor/mrs-neha-psychotherapist?specialization=Psychologist&practice_id=1146254&sem=true", 28.691452, 77.202430, "AntarMan Healthy Mind"),
  Doctor("assets/images/doctors/doc7.png", "Mr. Rajpal Kaushik", "18 Years", "Therapist", "M.Phil - Psychology", "Mr. Rajpal Kaushik is a Clinical Psychologist in Janakpuri, Delhi and has an experience of 16 years in this field. Mr. Rajpal Kaushik practices at West Delhi Psychiatry Centre in Janakpuri, Delhi and Kaushik Clinic in Janakpuri, Delhi. He completed M.Phil - Psychology from Annamalai Universtiy in 2011 and MA - Psychology from Maharshi Dayanand University, Rohtak in 1998. He has wide experience with all kinds of patients. He believes in having compassion and empathy towards clients and encourages a deep understanding of problems.", "11408 44821", "epione2022@gmail.com", "https://www.practo.com/delhi/therapist/rajpal-kaushik-psychologist?practice_id=1288787&specialization=Psychologist&referrer=doctor_listing&utm_source=google", 28.613384, 77.095920, "Kaushik Clinic"),
  Doctor("assets/images/doctors/doc8.png", "Dr. Diya Nangia Kapoor", "14 Years", "Therapist", "PhD - Psychology", "Dr. Diya Nangia Kapoor completed her M.Phil in Clinical Psychology from the prestigious NIMHANS, Bangalore. She further completed her Ph.D specializing in the treatment of OCD using Acceptance and Commitment Therapy. Her specializations include working with Adults, Adolescents and Children, for issues related to Clinical Psychology, Anxiety Disorders, Stress Management, Depression, Adolescent Well-Being, Mood Disorders, Personality Issues, Relationship Counselling, Family Counselling, Marital Counselling, etc. She actively uses Mindfulness techniques and meditation with CBT (Cognitive-Behavior Therapy), Emotion-Focused Therapy, ACT, etc, and believes in using an eclectic approach to psychotherapy and treatment of psychological problems.", "80 3729 6910", "epione2022@gmail.com", "https://www.practo.com/delhi/therapist/diya-kapoor-psychologist?practice_id=892812&specialization=Psychologist&referrer=doctor_listing&utm_source=google", 28.643377, 77.126410, "M Well"),
  Doctor("assets/images/doctors/doc9.png", "Mr. Nitin Anandi Lal", "6 Years", "Therapist", "M.Phil - Clinical Psychology", "Mr. Nitin Anandi Lal is a Psychologist in Greater Kailash Part 1, Delhi and has an experience of 6 years in this field. Mr. Nitin Anandi Lal practices at Udayan Mental Healthcare - Unleashing the Potential in Greater Kailash Part 1, Delhi and Max Super Speciality Hospital in Vaishali, Ghaziabad. He completed M.Phil - Clinical Psychology from Sri Ramachandra University, Chennai in 2016. He is a member of Rehabilitation Council of India (RCI) and Indian Association of Clinical Psychologists.", "11408 48837", "epione2022@gmail.com", "https://www.practo.com/delhi/therapist/nitin-40-psychologist?practice_id=1278665&specialization=Psychologist&referrer=doctor_listing&utm_source=google", 28.545470, 77.242340, "Udayan Mental Healthcare"),
  Doctor("assets/images/doctors/doc10.png", "Ms. Pakhi Jain", "8 Years", "Therapist", "MA - Psychology", "Ms. Pakhi Jain is a Psychologist & Hypnotherapist. She has completed her masters in Psychology. She pursuing her Ph.D. in “Positive Ageing” which talks about staying positive as you slowly step into the inevitable process known as aging. She mostly uses the technique of Talk Therapy along with certain techniques to find a solution to the current problem. As she says, There are no new fresh starts in life but new directions.", "11408 48834", "epione2022@gmail.com", "https://www.practo.com/delhi/therapist/dr-pakhi-jain-psychologist-1-psychologist?practice_id=1068492&specialization=Psychologist&referrer=doctor_listing&utm_source=google", 28.617086, 77.093300, "Unturned Stones")
  
];
